/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as IndexImport } from "./routes/index"
import { Route as DemosDemoImport } from "./routes/demos/$demo"

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any)

const DemosDemoRoute = DemosDemoImport.update({
  id: "/demos/$demo",
  path: "/demos/$demo",
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    "/demos/$demo": {
      id: "/demos/$demo"
      path: "/demos/$demo"
      fullPath: "/demos/$demo"
      preLoaderRoute: typeof DemosDemoImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/demos/$demo": typeof DemosDemoRoute
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/demos/$demo": typeof DemosDemoRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  "/": typeof IndexRoute
  "/demos/$demo": typeof DemosDemoRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/demos/$demo"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/demos/$demo"
  id: "__root__" | "/" | "/demos/$demo"
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemosDemoRoute: typeof DemosDemoRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemosDemoRoute: DemosDemoRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/demos/$demo"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/demos/$demo": {
      "filePath": "demos/$demo.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
