FROM debian:stable-slim

LABEL org.opencontainers.image.source=https://github.com/IBM/spnl
LABEL org.opencontainers.image.description="Span Query CLI with Ollama"
LABEL org.opencontainers.image.licenses="Apache-2.0"

ARG TARGET=target/release/spnl
ARG DEBIAN_FRONTEND=noninteractive

RUN apt update && \
    apt install -y ca-certificates curl lshw zstd && \
    curl -fsSL https://ollama.com/install.sh | sh && \
    apt remove -y ca-certificates curl && apt autoremove -y && \
    rm -rf /var/lib/apt/lists/*

RUN printf '#!/bin/sh\nollama serve > /dev/null 2> /dev/null & spnl $@\n' > /usr/local/bin/spnl.sh && chmod a+rx /usr/local/bin/spnl.sh
RUN groupadd -g 1001 spnl && useradd -u 1001 -g spnl spnl && mkdir /home/spnl && chown spnl /home/spnl

USER spnl

ARG SPNL_MODEL_BASE=smollm:135m
RUN ollama serve & sleep 5 ; ollama pull $SPNL_MODEL_BASE

ENV SPNL_BUILTIN=email2
ENV SPNL_MODEL=ollama/$SPNL_MODEL_BASE
ENV OLLAMA_NUM_PARALLEL=4

COPY $TARGET /usr/local/bin/spnl

ENTRYPOINT ["spnl.sh"]
