FROM debian:stable-slim

COPY target/release/spnl /usr/local/bin/spnl
RUN groupadd -g 1001 spnl && useradd -u 1001 -g spnl spnl && mkdir /home/spnl && chown spnl /home/spnl
USER spnl

LABEL org.opencontainers.image.source=https://github.com/IBM/spnl
LABEL org.opencontainers.image.description="Span Query CLI"
LABEL org.opencontainers.image.licenses="Apache-2.0"

ENV SPNL_BUILTIN=email2

ENTRYPOINT ["spnl"]
