ARG LLMD_VERSION=0.4.0
ARG MANYLINUX_VERSION=2_34 # use 2_39 for aarch64; TODO is it possible to infer this from the build platform?

# Python version extractor
FROM ghcr.io/llm-d/llm-d-cuda:v$LLMD_VERSION AS python_version
RUN python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")' > /tmp/llmd_python_version
RUN cat /tmp/llmd_python_version

# Builder
FROM quay.io/pypa/manylinux_$MANYLINUX_VERSION AS builder
ARG BUILD_RELEASE_ARG=" "
ENV BUILD_RELEASE_ARG=$BUILD_RELEASE_ARG
RUN dnf -y install pkgconfig protobuf-compiler openssl-devel
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
COPY --from=python_version /tmp/llmd_python_version /tmp/llmd_python_version
RUN cat /tmp/llmd_python_version
RUN pipx install maturin || pip$(cat /tmp/llmd_python_version) install maturin
COPY Cargo.* .
COPY spnl spnl
COPY cli cli
COPY benchmarks/haystack benchmarks/haystack
COPY web/wasm web/wasm
RUN --mount=type=cache,target=/root/.cargo/registry,sharing=locked \
    --mount=type=cache,target=/root/.cargo/git,sharing=locked \
    . "$HOME/.cargo/env" && maturin build $BUILD_RELEASE_ARG -m spnl/Cargo.toml --no-default-features -F tok,run_py -i python$(cat /tmp/llmd_python_version) --compatibility linux

# Main
FROM ghcr.io/llm-d/llm-d-cuda:v$LLMD_VERSION

LABEL org.opencontainers.image.source=https://github.com/IBM/spnl
LABEL org.opencontainers.image.description="Span Query support for llm-d's vLLM"
LABEL org.opencontainers.image.licenses="Apache-2.0"

ARG LLMD_VERSION=0.4.0 # sigh, we need to repeat this if we want to use it inside of the FROM

COPY --from=builder target/wheels/ /tmp/wheels
COPY docker/vllm/llm-d/patches/$LLMD_VERSION/ /tmp/patches
USER root
RUN cd /opt/vllm-source \
    && ls /tmp/patches \
    && for patchfile in /tmp/patches/*.patch.gz; do git apply <(gunzip -c $patchfile); done \
    && source /opt/vllm/bin/activate && python -m ensurepip --upgrade \
    && python3 -m pip install /tmp/wheels/*.whl
USER vllm
