name: CLI image build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# cancel any prior runs for this workflow and this PR (or branch)
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write  

env:
  RELEASE_VERSION: latest # this may overridden below

jobs:
  build_and_push_cli_image:
    name: build and push cli image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        containerfile:
          - Containerfile
          #- Containerfile.ollama
    steps:
      - uses: actions/checkout@v6

      - name: Disk space cleanup # https://dev.to/mathio/squeezing-disk-space-from-github-actions-runners-an-engineers-guide-3pjg
        run: ./.github/scripts/free-up-disk-space-fast.sh

      # Note: workflow_run does not have github.ref, hence the more complex logic to extract this information from head_branch.
      # See: https://github.com/orgs/community/discussions/158805#discussioncomment-13096586
      - name: Extract release tag to RELEASE_VERSION env var to detect whether head_branch is a tag
        id: detect
        shell: bash
        env:
          REF_NAME: ${{ github.event.workflow_run.head_branch }}
        run: |
          # exits 0 only if a tag with that name exists
          if git rev-parse -q --verify "refs/tags/${REF_NAME}" ; then
            # then this is a tag release
            echo "$RELEASE_VERSION=$REF_NAME" >> $GITHUB_ENV
          fi        
      - name: Verify RELEASE_VERSION
        run: echo "RELEASE_VERSION=$RELEASE_VERSION"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # We only need to log in if we are going to push
      - name: Login to Container Registry
        uses: docker/login-action@v3
        if: ${{ env.RELEASE_VERSION != 'latest' && github.event.workflow_run.conclusion == 'success' && !github.event.release.prerelease }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Container Image for CLI
        uses: docker/build-push-action@v6
        with:
          push: ${{ env.RELEASE_VERSION != 'latest' && github.event.workflow_run.conclusion == 'success' && !github.event.release.prerelease }}
          cache-from: type=gha                              # Use github action mechanisms to cache layers
          cache-to: type=gha,mode=max                       # Use github action mechanisms to cache layers
          tags: ghcr.io/ibm/spnl${{ matrix.containerfile == 'Containerfile' && '' || '-ollama' }}:${{ env.RELEASE_VERSION }},ghcr.io/ibm/spnl:latest
          file: ${{ matrix.containerfile }}
          platforms: linux/amd64,linux/arm64
